services:
  - type: web
    name: sorpresa-frontend
    env: node
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: node dist/sorpresa-frontend/server/server.mjs
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512
